
USE QuanLyNha
GO

IF OBJECT_ID('T32') IS NOT NULL
	DROP PROCEDURE T32
GO

CREATE PROCEDURE T32(@MaNha as int)
AS
BEGIN
	DECLARE @macsh int
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	BEGIN TRANSACTION
		SELECT @macsh = Ma_CSH FROM Nha Where ID = @MaNha
	COMMIT TRANSACTION
	return @macsh
END
GO


EXEC T32 1