/*T31*/
USE QuanLyNha
GO

IF OBJECT_ID('T32_Fix') IS NOT NULL
	DROP PROCEDURE T32_Fix
GO

CREATE PROCEDURE T32_Fix(@MaNha as int)
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED
	BEGIN TRANSACTION
		SELECT * FROM Nha Where ID = @MaNha
	COMMIT TRANSACTION
END
GO


EXEC T32_Fix 1